---
# tasks file for dns
- name: install software
  ansible.builtin.yum:
    name: 'dnsmasq'
    state: latest
- name: Add Host to DNS
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq_hosts.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "192.168.254.10 master master.example.com"
    - "192.168.254.11 git git.example.com"
    - "192.168.254.12 base0 base0.example.com"
    - "192.168.254.12 b0 b0.example.com"
    - "192.168.254.13 base1 base1.example.com"
    - "192.168.254.13 b1 b1.example.com"
    - "192.168.254.99 ansible ansible.example.com"
- name: copy config
  ansible.builtin.template:
    src: "dnsmasq-{{ item }}.j2"
    dest: "/etc/dnsmasq.d/{{ item }}.conf"
  with_items:
    - dns
- name: enable and start service
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - dnsmasq
- name: enable firewall
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - dns



